server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:api}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:yami_shops}?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 25000
      auto-commit: true
      connection-test-query: SELECT 1
  data:
    redis:
      host: ${REDIS_HOST:api}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
  ai:
    ollama:
      base-url: ${OLLAMA_HOST:http://localhost:11434}
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.8
logging:
  config: classpath:logback/logback-prod.xml
xxl-job:
  accessToken: ${XXL_JOB_ACCESS_TOKEN:default_token}
  logPath: ${XXL_JOB_LOG_PATH:/data/applogs/xxl-job/jobhandler}
  admin:
    addresses: ${XXL_JOB_ADDRESS:http://mall4j-job:8080/xxl-job-admin}

# 自定义配置
app:
  # JWT 配置
  jwt:
    # 通用 JWT 秘钥加密时使用的密钥
    secret-key: CommonJwt
    # 通用 JWT 过期时间（毫秒）
    ttl: 86400000  # 1天
    # 通用令牌名称
    token-name: token # 请求头中令牌名称

  alioss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    access-key-id: LATEST_ACCESS_KEY_ID
    access-key-secret: LATEST_ACCESS_KEY_SECRET
    bucket-name: real-time-lab-management-system

aliyun:
  access-key-id: XXX
  access-key-secret: XXX
  sms:
    signer-name: XXX # 短信签名
    template-code-phone-approve: XXX
    template-code-phone-reject: XXX
    template-code-code: XXX # 验证码发送模板code

# 文件服务配置
files:
  ip: localhost #ip
  port: 8080  #端口
  path: file  #访问路径 localhost:8080/file/xxx.jpg
  savePath: D://file/upload/ # 服务器图片路径配置 斜杠结尾